name: CI

on:
  push:
    branches: [main, renovate/**]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint

    steps:
      - uses: ./setup.yml
      - run: npm run lint

  type-checking:
    name: Type checking

    steps:
      - uses: ./setup.yml
      - run: npm run types:check

  build:
    name: Build

    steps:
      - uses: ./setup.yml
      - run: npm run build
