name: CI

on:
  push:
    branches: [main, renovate/**]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: "14.x"

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm ci
      - run: npm run lint

  type-checking:
    name: Type checking

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm ci
      - run: npm run types:check

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm ci
      - run: npm run build
