name: CI

on:
  push:
    branches: [main, renovate/**]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: IBM/pwa-lit-template/.github/workflows/setup.yml@reusing-workflows
      - run: npm run lint

  type-checking:
    name: Type checking

    runs-on: ubuntu-latest

    steps:
      - uses: IBM/pwa-lit-template/.github/workflows/setup.yml@reusing-workflows
      - run: npm run types:check

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: IBM/pwa-lit-template/.github/workflows/setup.yml@reusing-workflows
      - run: npm run build
