name: Setup

on:
  workflow_call:

env:
  NODE_VERSION: "14.x"

jobs:
  setup:
    name: Setup

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - run: npm ci
